# Generated by Django 5.2 on 2025-04-18 19:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checkout", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cart",
            name="total_price",
        ),
        migrations.RemoveField(
            model_name="cartitem",
            name="total_price",
        ),
        migrations.RemoveField(
            model_name="cartitem",
            name="unit_price",
        ),
        migrations.AddField(
            model_name="cart",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="cart",
            name="session_key",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="quantity",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
