# Generated by Django 5.2 on 2025-04-18 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "checkout",
            "0002_remove_cart_total_price_remove_cartitem_total_price_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
